### ISSUE TITLE
Fix intruction to publish new package

### ISSUE THREAD

**Issue by loicteixeira** [springload/wagtaildraftail#31]
It looks like `git release vx.y.z` requires some dependency? I got `git: 'release' is not a git command.`

Also, `make publish` fails:
```sh
$ make publish
dist
make: dist: No such file or directory
make: *** [publish] Error 1
```

**Comment by thibaudcolas** [comment]
Fixed. 

`git release` comes from https://github.com/tj/git-extras, which I love, but are indeed non-standard. I would advise on installing it, unfortunately `git release` directly pushes the tag and branch so it's not compatible with our branch protection which prevents direct push. I have replaced it with the branch protection friendly workflow, based on https://github.com/springload/eslint-config-springload.

`Makefile` are an enigma from another age of software dev so you'll still be discovering quirks in 10 years time. Fun fact: The editorconfig is set to have tabs in `Makefile`s, because they require tabs to be used.
